name: clifs
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
  - rapidsai

dependencies:
  - python=3.10
  - pandas
  - ipykernel
  - spacy
  - spacy-model-en_core_web_sm
  - scikit-learn=1.6.1
  - conda-forge::gensim
  - nltk
  - openai
  - pytorch=2.1
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cuml=24.02

  - pytorch::faiss-gpu
  - pip:
    - sentence-transformers

# note, will also need
# pip install git+https://github.com/huggingface/transformers.git@31ab7168ff7e07f61c90134e5238c4d97606aa70